// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

#![allow(proc_macro_derive_resolution_fallback)]

//! This crate's entire purpose is to seed the
//! [libellis](https://github.com/libellis/libellis-backend) database with fake data (generated by
//! [faker](https://github.com/tikotzky/faker-rs) library).
//!
//! ## Setup
//!
//! You MUST set your `DATABASE_URL` environment variable to your libellis postgres database.
//!
//! ### Example
//! ```terminal
//! $ export DATABASE_URL=postgres://username:password@localhost/libellis
//! ```
//!
//! You can optionally set this in a `.env` file in the root folder of this project if you are
//! running the project from a local folder.
//!
//! ## Installation
//!
//! You may install this in one of two ways. If you have `cargo` installed then it's very easy. If
//! not, you can install rust and cargo by following this very simple [cargo setup](https://doc.rust-lang.org/cargo/getting-started/installation.html) process.
//! Once you have cargo installed you can install this terminal application by running:
//!
//! ```terminal
//! $ cargo install birdseed
//! ```
//!
//! Optionally you may instead clone this repo and in the root directory build the release version
//! of this crate:
//!
//! ```terminal
//! $ git clone https://github.com/libellis/birdseed.git
//! $ cd birdseed
//! $ cargo build --release
//! ```
//!
//! ## Features
//!
//! ### `feed`
//!
//! You can seed all databases with the `feed` subcommand:
//!
//! ```terminal
//! $ birdseed feed
//! ```
//!
//! We can specify a row count (overriding the default of 1000 rows):
//!
//! ```terminal
//! $ birdseed feed -r 10000
//! ```
//!
//! In this exampe we override the default of 1,000 rows and instead seed 10,000 rows.
//!
//! Note: What the row count really means is that we will seed row count amount of users, surveys
//! and questions, but row count * 4 amount of choices and votes.
//!
//! ### `clear`
//!
//! You can clear all tables with the `clear` subcommand:
//!
//! ```terminal
//! $ birdseed clear
//! ```
//!
//! ### `rebuild`
//!
//! You can rebuild all tables according to embedded diesel migrations
//!
//! ```terminal
//! $ birdseed rebuild
//! ```

#[macro_use]
extern crate structopt;

#[macro_use]
extern crate diesel;
extern crate dotenv;

#[macro_use]
extern crate diesel_migrations;

#[macro_use]
extern crate fake;

extern crate indicatif;
extern crate rand;

use diesel::pg::PgConnection;
use diesel::prelude::*;
use dotenv::dotenv;
use std::env;

use std::error::Error;
use structopt::StructOpt;

use rand::seq::SliceRandom;
use rand::thread_rng;

use indicatif::{ProgressBar, ProgressStyle};

/// re-export of diesel models
pub mod models;

/// re-export of diesel schema
pub mod schema;

embed_migrations!("./migrations");

use self::models::{
    Choice, NewChoice, NewQuestion, NewSurvey, NewUser, NewVote, Question, Survey, User, Vote,
};

#[derive(StructOpt, Debug)]
#[structopt(
    name = "birdseed",
    about = "The libellis database seeder",
    long_about = "You can use birdseed to seed a libellis db with junk data!"
)]
/// You can use birdseed to seed a libellis db with junk data!
pub enum Birdseed {
    #[structopt(name = "feed")]
    /// Seeds random data into all tables
    Feed {
        /// How many rows to inject
        #[structopt(short = "r", long = "rows", default_value = "1000")]
        row_count: u32,
    },

    #[structopt(name = "clear")]
    /// Clears all tables in libellis database
    Clear,

    #[structopt(name = "rebuild")]
    /// Rebuilds all tables per most recent schema (embedded in binary)
    Rebuild,
}

/// `run` will take in a Birdseed enum config (parsed in `main`) and either clear all tables or
/// populate all tables with number of rows specified in -r (1000 by default)
pub fn run(config: Birdseed) -> Result<(), Box<dyn Error>> {
    let connection = establish_connection();

    match config {
        Birdseed::Feed { row_count } => populate_all(&connection, row_count),
        Birdseed::Clear => clear_all(&connection),
        Birdseed::Rebuild => rebuild(&connection),
    }
}

// Kicks off populating all tables and updating user with visual progress
// bar along the way
fn populate_all(conn: &PgConnection, row_count: u32) -> Result<(), Box<dyn Error>> {
    println!("\r\n                  🐦 Seeding All Tables 🐦\r\n");

    let bar = ProgressBar::new((row_count * 11) as u64);
    bar.set_style(
        ProgressStyle::default_bar()
            .template("[{elapsed_precise}] {bar:40.cyan/blue} {msg}")
            .progress_chars("##-"),
    );

    let usernames = populate_users(&conn, row_count, &bar)?;
    let survey_ids = populate_surveys(&conn, &usernames, row_count, &bar)?;
    let question_ids = populate_questions(&conn, &survey_ids, row_count, &bar)?;
    let choice_ids = populate_choices(&conn, &question_ids, row_count, &bar)?;
    populate_votes(&conn, &usernames, &choice_ids, &bar)?;
    bar.finish();
    println!("\r\n             🐦 Birdseed has finished seeding! 🐦\r\n");
    Ok(())
}

// Clears all tables in appropraite order
fn clear_all(conn: &PgConnection) -> Result<(), Box<dyn Error>> {
    use schema::*;

    diesel::delete(votes::table).execute(conn)?;
    diesel::delete(choices::table).execute(conn)?;
    diesel::delete(questions::table).execute(conn)?;
    diesel::delete(surveys::table).execute(conn)?;
    diesel::delete(users::table).execute(conn)?;

    Ok(())
}

// Drops all tables from libellis database
fn drop_all(conn: &PgConnection) {
    conn.execute("DROP VIEW users_votes");
    conn.execute("DROP TABLE votes");
    conn.execute("DROP TABLE choices");
    conn.execute("DROP TABLE questions");
    conn.execute("DROP TABLE surveys");
    conn.execute("DROP TABLE users");
    conn.execute("DROP TABLE __diesel_schema_migrations");
}

// Rebuilds all tables per most recent embedded diesel migrations
fn rebuild(conn: &PgConnection) -> Result<(), Box<dyn Error>> {
    drop_all(conn);
    embedded_migrations::run(conn)?;
    Ok(())
}

// Populates users table with row_count random users
fn populate_users(
    conn: &PgConnection,
    row_count: u32,
    bar: &ProgressBar,
) -> Result<Vec<String>, Box<dyn Error>> {
    let mut usernames = Vec::new();
    bar.set_message(&format!("Seeding {} users", row_count));
    for _ in 0..row_count {
        let user = format!(
            "{}{}",
            fake!(Internet.user_name),
            fake!(Number.between(90, 9999))
        );
        let pw = format!(
            "{}{}",
            fake!(Name.name),
            fake!(Number.between(10000, 99999))
        );
        let em = format!("{}@gmail.com", user);
        let first = format!("{}", fake!(Name.first_name));
        let last = format!("{}", fake!(Name.last_name));

        create_user(conn, &user, &pw, &em, &first, &last);
        usernames.push(user);
        bar.inc(1);
    }

    Ok(usernames)
}

// Populates surveys table with row_count random surveys making sure each survey is being created
// by an existing user
fn populate_surveys(
    conn: &PgConnection,
    authors: &Vec<String>,
    row_count: u32,
    bar: &ProgressBar,
) -> Result<Vec<i32>, Box<dyn Error>> {
    let mut survey_ids = Vec::new();
    bar.set_message(&format!("Seeding {} surveys", row_count));
    for i in 0..row_count as usize {
        let auth = &authors[i];
        let survey_title = format!("{}", fake!(Lorem.sentence(4, 8)));
        let survey = create_survey(conn, auth, &survey_title);
        survey_ids.push(survey.id);
        bar.inc(1);
    }

    Ok(survey_ids)
}

// Populates questions table with row_count random questions ensuring that each question relates to
// an existing survey
fn populate_questions(
    conn: &PgConnection,
    survey_ids: &Vec<i32>,
    row_count: u32,
    bar: &ProgressBar,
) -> Result<Vec<i32>, Box<dyn Error>> {
    let mut question_ids = Vec::new();
    bar.set_message(&format!("Seeding {} questions", row_count));
    for i in 0..row_count as usize {
        let s_id = survey_ids[i];
        let q_title = format!("{}", fake!(Lorem.sentence(3, 7)));
        let q_type = "multiple".to_string();
        let question = create_question(conn, s_id, &q_type, &q_title);
        question_ids.push(question.id);
        bar.inc(1);
    }

    Ok(question_ids)
}

// Populates choices table with row_count * 4 random choices ensuring that each question relates to
// an existing survey
fn populate_choices(
    conn: &PgConnection,
    question_ids: &Vec<i32>,
    row_count: u32,
    bar: &ProgressBar,
) -> Result<Vec<i32>, Box<dyn Error>> {
    let mut choice_ids = Vec::new();
    bar.set_message(&format!("Seeding {} choices", (row_count * 4)));
    for i in 0..row_count as usize {
        let q_id = question_ids[i];
        // For each question, inject 4 random text choices
        for _ in 0..4 {
            let c_title = format!("{}", fake!(Lorem.sentence(1, 4)));
            let c_type = "text".to_string();
            let choice = create_choice(conn, q_id, &c_type, &c_title);
            choice_ids.push(choice.id);
            bar.inc(1);
        }
    }

    Ok(choice_ids)
}

// Populates the votes table with real votes from our newly inserted random users who vote on
// choices in a semi-randomish way (not that random really)
fn populate_votes(
    conn: &PgConnection,
    authors: &Vec<String>,
    choice_ids: &Vec<i32>,
    bar: &ProgressBar,
) -> Result<(), Box<dyn Error>> {
    bar.set_message(&format!("{} users are voting", (authors.len())));

    // Create vectors of idx and shuffle them
    let mut rng = thread_rng();
    let mut choice_idxs: Vec<usize> = (0..choice_ids.len()).collect();
    let choice_slice: &mut [usize] = &mut choice_idxs;
    let mut author_idxs: Vec<usize> = (0..authors.len()).collect();
    let author_slice: &mut [usize] = &mut author_idxs;
    choice_slice.shuffle(&mut rng);
    author_slice.shuffle(&mut rng);

    // For each round up randomize the choice and the author voting
    // on the choice
    for i in 0..authors.len() - 1 {
        let name = &authors[author_slice[i]];
        for j in 1..=4 {
            let c_id = choice_ids[choice_slice[(i + 1) * j]];
            create_vote(conn, c_id, name, 1);
            bar.inc(1);
        }
    }

    Ok(())
}

// Establishes a connection to the libellis postgres database on your machine, as specified by your
// DATABASE_URL environment variable.
fn establish_connection() -> PgConnection {
    dotenv().ok();

    let database_url = env::var("DATABASE_URL").expect("DATABASE_URL must be set");

    PgConnection::establish(&database_url).expect(&format!("Error connecting to {}", database_url))
}

/**
 * The following series of functions are very simple - each one simply creates a single
 * user/survey/question/choice/vote
 */
fn create_user<'a>(
    conn: &PgConnection,
    user: &'a str,
    pw: &'a str,
    em: &'a str,
    first: &'a str,
    last: &'a str,
) -> User {
    use schema::users;

    let new_user = NewUser {
        username: user,
        password: pw,
        email: em,
        first_name: first,
        last_name: last,
        is_admin: false,
    };

    diesel::insert_into(users::table)
        .values(&new_user)
        .get_result(conn)
        .expect("Error saving new user")
}

fn create_survey<'a>(conn: &PgConnection, auth: &'a str, survey_title: &'a str) -> Survey {
    use schema::surveys;

    let new_survey = NewSurvey {
        author: auth,
        title: survey_title,
    };

    diesel::insert_into(surveys::table)
        .values(&new_survey)
        .get_result(conn)
        .expect("Error saving new survey")
}

fn create_question<'a>(
    conn: &PgConnection,
    s_id: i32,
    q_type: &'a str,
    q_title: &'a str,
) -> Question {
    use schema::questions;

    let new_question = NewQuestion {
        survey_id: s_id,
        type_: q_type,
        title: q_title,
    };

    diesel::insert_into(questions::table)
        .values(&new_question)
        .get_result(conn)
        .expect("Error saving new question")
}

fn create_choice<'a>(conn: &PgConnection, q_id: i32, c_type: &'a str, c_title: &'a str) -> Choice {
    use schema::choices;

    let new_choice = NewChoice {
        question_id: q_id,
        type_: c_type,
        title: c_title,
    };

    diesel::insert_into(choices::table)
        .values(&new_choice)
        .get_result(conn)
        .expect("Error saving new choice")
}

fn create_vote<'a>(conn: &PgConnection, c_id: i32, name: &'a str, points: i32) -> Vote {
    use schema::votes;

    let new_vote = NewVote {
        choice_id: c_id,
        username: name,
        score: points,
    };

    diesel::insert_into(votes::table)
        .values(&new_vote)
        .get_result(conn)
        .expect("Error saving new vote")
}
